# Generated by Django 5.1 on 2024-09-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_de_fabrication',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='product',
            name='prixHT',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productitem',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
