# Generated by Django 5.1 on 2024-09-10 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTp1', '0002_product_date_de_fabrication_product_prixht_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='statut',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appTp1.statut'),
        ),
    ]
