# Generated by Django 5.1 on 2024-09-10 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTp1', '0003_statut_product_statut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='productitem',
            options={'verbose_name': 'Déclinaison Produit'},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_de_fabrication',
            field=models.DateField(blank=True, default='2024-01-01', verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prixHT',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix Unitaire HT'),
        ),
        migrations.AlterField(
            model_name='product',
            name='statut',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='appTp1.statut'),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='statut',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
