# Generated by Django 5.1 on 2024-09-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTp1', '0004_alter_product_options_alter_productitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
