# Generated by Django 5.1 on 2024-09-12 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTp1', '0005_alter_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Attribut',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_de_fabrication',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prixHT',
        ),
        migrations.AddField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date création'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ht',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix unitaire HT'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_ttc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix unitaire TTC'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Out of stock')], default=0),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Position')),
                ('product_attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTp1.productattribute', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Valeur attribut',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='product_item', to='appTp1.productattributevalue'),
        ),
        migrations.DeleteModel(
            name='Statut',
        ),
    ]
