# Generated by Django 5.1 on 2024-09-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appTp1', '0006_productattribute_status_remove_product_statut_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='color',
        ),
    ]
