# Generated by Django 5.1 on 2024-10-08 06:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appTp1', '0007_remove_productitem_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProductFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTp1.fournisseur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTp1.product')),
            ],
            options={
                'verbose_name': 'Produit Fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date commande')),
                ('quantity', models.IntegerField(default=0)),
                ('etat', models.SmallIntegerField(choices=[(0, 'En Préparation'), (1, 'Passée'), (2, 'Reçue')], default=0)),
                ('product_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appTp1.productfournisseur')),
            ],
            options={
                'verbose_name': 'Commande',
            },
        ),
    ]
